name: "Build and Test"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '35 19 * * 4'

jobs:
  analyze:
    name: Analyze
    runs-on: windows-2022

    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp' ]
        targetplatform: [ x86, x64 ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Install workloads
      run: dotnet workload install maui

    - name: Build
      run: |
        dotnet build ./samples/AvaloniaSample
        dotnet build ./samples/BlazorSample
        dotnet build ./samples/MauiSample
        dotnet build ./samples/WinFormsSample
        dotnet build ./samples/WPFSample
        dotnet build ./samples/XamarinSample/XamarinSample/XamarinSample
        dotnet build ./samples/EtoFormsSample
        msbuild ./samples/UWPSample/UWPSample.csproj /t:Restore
        msbuild ./samples/WinUISample/WinUI/WinUI/WinUISample.csproj /t:Restore

    - name: Run unit tests
      run: dotnet test ./tests/LiveChartsCore.UnitTesting
