name: "Build and Test"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '35 19 * * 4'

jobs:
  analyze:
    name: Analyze
    runs-on: windows-2022

    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp' ]
        targetplatform: [ x86, x64 ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Install workloads
      run: |
        dotnet workload install maui
        dotnet workload install wasm-tools

    - name: Build Avalonia
      run: dotnet build ./samples/AvaloniaSample

    - name: Build Blazor
      run: dotnet build ./samples/BlazorSample

    - name: Build Maui
      run: dotnet build ./samples/MauiSample

    - name: Build WinForms
      run: dotnet build ./samples/WinFormsSample

    - name: Build WPF
      run: dotnet build ./samples/WPFSample

    - name: Build Xamarin
      run: dotnet build ./samples/XamarinSample/XamarinSample/XamarinSample

    - name: Build EtoForms
      run: dotnet build ./samples/EtoFormsSample

    - name: Build UWP
      run: msbuild ./samples/UWPSample/UWPSample.csproj /t:Restore

    - name: Build WinUI
      run: msbuild ./samples/WinUISample/WinUI/WinUI/WinUISample.csproj /t:Restore

    - name: Run unit tests
      run: dotnet test ./tests/LiveChartsCore.UnitTesting
