name: "Buid all views"

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]
  schedule:
    - cron: '35 19 * * 4'

jobs:
  analyze:
    name: Analyze
    runs-on: windows-2022

    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp' ]
        targetplatform: [ x86, x64 ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Run unit tests
      run: ./pack.ps1
