name: "MAUI"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  analyze:
    name: Analyze
    runs-on: windows-2022

    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp' ]
        targetplatform: [ x86, x64 ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    #- uses: actions/setup-dotnet@v1
    #  with:
    #    dotnet-version: '6.0.x'

    #- name: Add msbuild to PATH
    #  uses: microsoft/setup-msbuild@v1.1
    #  with:
    #    vs-version: '[17.1.0,17.2.0)'
    #    vs-prerelease: true

    - name: Build assemblies
      run: |
        dotnet build ./src/skiasharp/LiveChartsCore.SkiaSharpView.Maui --configuration Release

    - name: Build Samples
      run: |
        dotnet build ./samples/MauiSample --configuration Release
