name: "WinUI"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '35 19 * * 4'

jobs:
  analyze:
    name: Analyze
    runs-on: windows-2022

    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp' ]
        targetplatform: [ x86, x64 ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install workloads
      run: |
        dotnet workload install maui --from-rollback-file https://aka.ms/dotnet/maui/preview.10.json --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    # Workaround use ms build instead, it seems that dotnet build is not ready yet
    #- name: Build assemblies
    #  run: |
    #    dotnet build ./src/skiasharp/LiveChartsCore.SkiaSharpVew.WinUI --configuration Release

    - name: Build assemblies
      run: |
        msbuild ./src/skiasharp/LiveChartsCore.SkiaSharpVew.WinUI -property:Configuration=Release
